source 'https://rubygems.org'

gem 'rake', '10.4.2'
gem 'puppet', '3.8.2'
gem 'rspec-puppet', '~> 2.2.0'
gem 'rspec-puppet-facts', '~> 0.11.0'
gem 'rspec-core', '~> 3.2.0'
gem 'puppet-lint', '~> 1.1.0'
gem 'metadata-json-lint', '~> 0.0.6'
gem 'puppetlabs_spec_helper', '~> 0.10'
